# Generated by Django 4.1.5 on 2023-01-08 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstats",
            name="track",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="monitor.websites"
            ),
        ),
    ]
