# Generated by Django 4.1.5 on 2023-01-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0004_alter_notifygroup_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalstats",
            old_name="down_counts",
            new_name="downtime_counts",
        ),
        migrations.RenameField(
            model_name="historicalstats",
            old_name="up_counts",
            new_name="uptime_counts",
        ),
    ]
