# Generated by Django 4.1.5 on 2023-01-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0006_authenticationschema_websites_has_authentication"),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticationschema",
            name="token_auth",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="websites",
            name="auth_types",
            field=models.CharField(
                choices=[
                    ("basic", "Basic Auth"),
                    ("token", "Token Auth"),
                    ("bearer", "Jwt Auth"),
                ],
                max_length=6,
                null=True,
            ),
        ),
    ]
