# Generated by Django 4.1.5 on 2023-01-11 00:49

import apps.monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0007_authenticationschema_token_auth_websites_auth_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("site", models.URLField(unique=True)),
                (
                    "basic_auth",
                    models.JSONField(
                        blank=True,
                        default="",
                        null=True,
                    ),
                ),
                ("token_auth", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "bearer_auth",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Authentication Schemes",
                "db_table": "authentication_schemes",
            },
        ),
        migrations.DeleteModel(
            name="AuthenticationSchema",
        ),
    ]
