# Generated by Django 4.1.5 on 2023-01-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0008_authenticationscheme_delete_authenticationschema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authenticationscheme",
            name="basic_auth",
        ),
        migrations.RemoveField(
            model_name="websites",
            name="auth_types",
        ),
        migrations.AddField(
            model_name="authenticationscheme",
            name="session_auth",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="websites",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("up", "Up"), ("down", "Down")],
                max_length=4,
                null=True,
            ),
        ),
    ]
